name: Deploy site

# 当 main 分支有 push 时触发
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ 安装 Ruby
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'   # al-folio 要求 ruby >= 3.1

      # 3️⃣ 安装 bundler 并安装依赖
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # 4️⃣ 使用 Jekyll 构建网站
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      # 5️⃣ 推送 _site 到 gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
